version: '3'

services:
  passport:
    container_name: lghs-passport
    build: ./.docker
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    networks:
      - net

volumes:
  database_data:

networks:
  net:
