version: '3'

tasks:
  watch:
    cmds:
      - docker compose up passport
    silent: true

  composer:install:
    cmds:
      - docker run  --init --rm -w /var/www/html -v $(pwd):/var/www/html lghs-passport composer install
    silent: true
